[package]
name = "intro-logistic-closures"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
diffsol = { path = "../../diffsol" }
nalgebra = { workspace = true }
plotly = { workspace = true }