[book]
authors = ["martinjrobins"]
language = "en"
multilingual = false
src = "src"
title = "DiffSol"

[output.html]
mathjax-support = true

[preprocessor.keeper]
command = "mdbook-keeper"
manifest_dir = "."
externs = ["diffsol", "nalgebra", "faer", "plotly"]
# is_workspace = true
# build_features = ["plotly"]

